In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [2]:
df=pd.read_csv('Social_Network_Ads.csv')
df=pd.get_dummies(df,dtype=int,drop_first=True)
df

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [3]:
indep=df[['User ID','Age','EstimatedSalary','Gender_Male']]
dep=df['Purchased']

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=3)

Naive_bayes

In [5]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB
param_grid = {'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5] 
   }
grid=GridSearchCV(GaussianNB(),param_grid,refit = True, verbose = 3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


GridSearchCV(estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': [1e-09, 1e-08, 1e-07, 1e-06, 1e-05]},
             scoring='f1_weighted', verbose=3)

In [6]:
re=grid.cv_results_
y_pred=grid.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

from sklearn.metrics import f1_score
fs=f1_score(y_test,y_pred,average='weighted')
print("The f1_macro value for the best parameters {}:".format(grid.best_params_),fs)



[[81  7]
 [ 9 37]]
              precision    recall  f1-score   support

           0       0.90      0.92      0.91        88
           1       0.84      0.80      0.82        46

    accuracy                           0.88       134
   macro avg       0.87      0.86      0.87       134
weighted avg       0.88      0.88      0.88       134

The f1_macro value for the best parameters {'var_smoothing': 1e-09}: 0.8799411183781467


In [7]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(0.9419466403162056)

In [8]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.005905      0.000980         0.006717        0.001504   
1       0.005927      0.002188         0.006409        0.001976   
2       0.004339      0.000655         0.007099        0.002594   
3       0.011396      0.013253         0.007721        0.000536   
4       0.005183      0.001445         0.006167        0.001644   

   param_var_smoothing                    params  split0_test_score  \
0         1.000000e-09  {'var_smoothing': 1e-09}           0.869648   
1         1.000000e-08  {'var_smoothing': 1e-08}           0.832404   
2         1.000000e-07  {'var_smoothing': 1e-07}           0.728375   
3         1.000000e-06  {'var_smoothing': 1e-06}           0.721979   
4         1.000000e-05  {'var_smoothing': 1e-05}           0.721979   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.865054           0.943699           0.844370           0.883738   
1           0.813763           0.885265           0.844370           0.863141   
2           0.764624           0.755313           0.778706           0.774778   
3           0.764624           0.755313           0.801281           0.774778   
4           0.764624           0.755313           0.801281           0.774778   

   mean_test_score  std_test_score  rank_test_score  
0         0.881302        0.033654                1  
1         0.847789        0.024683                2  
2         0.760359        0.017951                5  
3         0.763595        0.025872                3  
4         0.763595        0.025872                3

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import BernoulliNB
param_grid = { 'alpha': [0.5, 1.0, 1.5, 2.0], 
    'binarize': [0.0, 0.5, 1.0]  
   }
grid=GridSearchCV(BernoulliNB(),param_grid,refit = True, verbose = 3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [0.5, 1.0, 1.5, 2.0],
                         'binarize': [0.0, 0.5, 1.0]},
             scoring='f1_weighted', verbose=3)

In [10]:
re=grid.cv_results_
y_pred=grid.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

from sklearn.metrics import f1_score
fs=f1_score(y_test,y_pred,average='weighted')
print("The f1_macro value for the best parameters {}:".format(grid.best_params_),fs)

from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

[[88  0]
 [46  0]]
              precision    recall  f1-score   support

           0       0.66      1.00      0.79        88
           1       0.00      0.00      0.00        46

    accuracy                           0.66       134
   macro avg       0.33      0.50      0.40       134
weighted avg       0.43      0.66      0.52       134

The f1_macro value for the best parameters {'alpha': 0.5, 'binarize': 0.0}: 0.5206400430281027


C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:153

np.float64(0.4053853754940711)

In [11]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0        0.004735      0.000245         0.004834        0.000509          0.5   
1        0.006122      0.001992         0.006014        0.001301          0.5   
2        0.003614      0.000493         0.004736        0.000442          0.5   
3        0.003700      0.000684         0.003623        0.000334          1.0   
4        0.004358      0.001053         0.004455        0.000715          1.0   
5        0.002931      0.000481         0.004110        0.001119          1.0   
6        0.004546      0.001329         0.006210        0.001847          1.5   
7        0.003990      0.000892         0.004915        0.002051          1.5   
8        0.003021      0.000318         0.004101        0.000473          1.5   
9        0.002883      0.000390         0.004877        0.000807          2.0   
10       0.004181      0.001341         0.004069        0.000657          2.0   
11       0.003266      0.000790         0.003390        0.000489          2.0   

    param_binarize                           params  split0_test_score  \
0              0.0  {'alpha': 0.5, 'binarize': 0.0}           0.486532   
1              0.5  {'alpha': 0.5, 'binarize': 0.5}           0.486532   
2              1.0  {'alpha': 0.5, 'binarize': 1.0}           0.486532   
3              0.0  {'alpha': 1.0, 'binarize': 0.0}           0.486532   
4              0.5  {'alpha': 1.0, 'binarize': 0.5}           0.486532   
5              1.0  {'alpha': 1.0, 'binarize': 1.0}           0.486532   
6              0.0  {'alpha': 1.5, 'binarize': 0.0}           0.486532   
7              0.5  {'alpha': 1.5, 'binarize': 0.5}           0.486532   
8              1.0  {'alpha': 1.5, 'binarize': 1.0}           0.486532   
9              0.0  {'alpha': 2.0, 'binarize': 0.0}           0.486532   
10             0.5  {'alpha': 2.0, 'binarize': 0.5}           0.486532   
11             1.0  {'alpha': 2.0, 'binarize': 1.0}           0.486532   

    split1_test_score  split2_test_score  split3_test_score  \
0             0.50141            0.50141            0.50141   
1             0.50141            0.50141            0.50141   
2             0.50141            0.50141            0.50141   
3             0.50141            0.50141            0.50141   
4             0.50141            0.50141            0.50141   
5             0.50141            0.50141            0.50141   
6             0.50141            0.50141            0.50141   
7             0.50141            0.50141            0.50141   
8             0.50141            0.50141            0.50141   
9             0.50141            0.50141            0.50141   
10            0.50141            0.50141            0.50141   
11            0.50141            0.50141            0.50141   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.477841          0.49372         0.00981                1  
1            0.477841          0.49372         0.00981                1  
2            0.477841          0.49372         0.00981                1  
3            0.477841          0.49372         0.00981                1  
4            0.477841          0.49372         0.00981                1  
5            0.477841          0.49372         0.00981                1  
6            0.477841          0.49372         0.00981                1  
7            0.477841          0.49372         0.00981                1  
8            0.477841          0.49372         0.00981                1  
9            0.477841          0.49372         0.00981                1  
10           0.477841          0.49372         0.00981                1  
11           0.477841          0.49372         0.00981                1

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB
param_grid = { 'alpha': [0.5, 1.0, 1.5, 2.0] 
   }
grid=GridSearchCV(MultinomialNB(),param_grid,refit = True, verbose = 3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


GridSearchCV(estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.5, 1.0, 1.5, 2.0]}, scoring='f1_weighted',
             verbose=3)

In [13]:
re=grid.cv_results_
y_pred=grid.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

from sklearn.metrics import f1_score
fs=f1_score(y_test,y_pred,average='weighted')
print("The f1_macro value for the best parameters {}:".format(grid.best_params_),fs)

from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

[[58 30]
 [17 29]]
              precision    recall  f1-score   support

           0       0.77      0.66      0.71        88
           1       0.49      0.63      0.55        46

    accuracy                           0.65       134
   macro avg       0.63      0.64      0.63       134
weighted avg       0.68      0.65      0.66       134

The f1_macro value for the best parameters {'alpha': 0.5}: 0.656979781199175


np.float64(0.6384634387351779)

In [14]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0       0.003523  4.548516e-04         0.004134        0.000454          0.5   
1       0.003264  4.882295e-04         0.004654        0.000718          1.0   
2       0.003854  6.409656e-04         0.004059        0.000390          1.5   
3       0.002992  5.001110e-07         0.002933        0.000367          2.0   

           params  split0_test_score  split1_test_score  split2_test_score  \
0  {'alpha': 0.5}           0.599449           0.593122           0.665937   
1  {'alpha': 1.0}           0.599449           0.593122           0.665937   
2  {'alpha': 1.5}           0.599449           0.593122           0.665937   
3  {'alpha': 2.0}           0.599449           0.593122           0.665937   

   split3_test_score  split4_test_score  mean_test_score  std_test_score  \
0           0.795256           0.718256         0.674404        0.075927   
1           0.795256           0.718256         0.674404        0.075927   
2           0.795256           0.718256         0.674404        0.075927   
3           0.795256           0.718256         0.674404        0.075927   

   rank_test_score  
0                1  
1                1  
2                1  
3                1

In [25]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import CategoricalNB
param_grid = {'force_alpha':[True,False],
              'fit_prior':[True,False],
              'min_categories':[None],
            }
grid=GridSearchCV(CategoricalNB(),param_grid,refit = True, verbose = 3, n_jobs=-1, scoring='f1_weighted')
grid.fit(indep,dep)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_search.py:1103: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan]
  warnings.warn(


GridSearchCV(estimator=CategoricalNB(), n_jobs=-1,
             param_grid={'fit_prior': [True, False],
                         'force_alpha': [True, False],
                         'min_categories': [None]},
             scoring='f1_weighted', verbose=3)

In [26]:
re=grid.cv_results_
y_pred=grid.predict(indep)

In [29]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(dep,y_pred)
print(cm)

from sklearn.metrics import classification_report
cr=classification_report(dep,y_pred)
print(cr)


[[254   3]
 [ 17 126]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.96       257
           1       0.98      0.88      0.93       143

    accuracy                           0.95       400
   macro avg       0.96      0.93      0.94       400
weighted avg       0.95      0.95      0.95       400



In [31]:
from sklearn.metrics import f1_score
fs=f1_score(dep,y_pred,average='weighted')
print("The f1_macro value for the best parameters {}:".format(grid.best_params_),fs)

from sklearn.metrics import roc_auc_score
roc_auc_score(dep,grid.predict_proba(indep)[:,1])

The f1_macro value for the best parameters {'fit_prior': True, 'force_alpha': True, 'min_categories': None}: 0.9493761140819964


np.float64(0.9929933879350222)

In [32]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       9.172574      0.095540         0.152706        0.044260   
1       8.082369      1.215759         0.234930        0.047098   
2       6.524218      0.152473         0.266364        0.053094   
3       2.695066      1.759624         0.044203        0.073212   

   param_fit_prior  param_force_alpha param_min_categories  \
0             True               True                 None   
1             True              False                 None   
2            False               True                 None   
3            False              False                 None   

                                              params  split0_test_score  \
0  {'fit_prior': True, 'force_alpha': True, 'min_...           0.690376   
1  {'fit_prior': True, 'force_alpha': False, 'min...           0.690376   
2  {'fit_prior': False, 'force_alpha': True, 'min...           0.767183   
3  {'fit_prior': False, 'force_alpha': False, 'mi...           0.767183   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                NaN           0.780251           0.747940           0.773146   
1                NaN           0.780251           0.747940           0.773146   
2                NaN           0.859227           0.753906           0.754419   
3                NaN           0.859227           0.753906           0.754419   

   mean_test_score  std_test_score  rank_test_score  
0              NaN             NaN                1  
1              NaN             NaN                1  
2              NaN             NaN                1  
3              NaN             NaN                1

In [17]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import ComplementNB
param_grid = { 'alpha': [0.1, 0.5, 1.0, 1.5, 2.0],
              'norm': [True, False]
   }
grid=GridSearchCV(ComplementNB(),param_grid,refit = True, verbose = 3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


GridSearchCV(estimator=ComplementNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.5, 1.0, 1.5, 2.0],
                         'norm': [True, False]},
             scoring='f1_weighted', verbose=3)

In [18]:
re=grid.cv_results_
y_pred=grid.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

from sklearn.metrics import f1_score
fs=f1_score(y_test,y_pred,average='weighted')
print("The f1_macro value for the best parameters {}:".format(grid.best_params_),fs)

from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

[[58 30]
 [17 29]]
              precision    recall  f1-score   support

           0       0.77      0.66      0.71        88
           1       0.49      0.63      0.55        46

    accuracy                           0.65       134
   macro avg       0.63      0.64      0.63       134
weighted avg       0.68      0.65      0.66       134

The f1_macro value for the best parameters {'alpha': 0.1, 'norm': False}: 0.656979781199175


np.float64(0.6384634387351779)

In [19]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0       0.008687      0.002795         0.006823        0.002418          0.1   
1       0.004240      0.000859         0.005383        0.001246          0.1   
2       0.003233      0.000234         0.004380        0.001491          0.5   
3       0.003565      0.000664         0.003894        0.001108          0.5   
4       0.003136      0.000198         0.003555        0.000390          1.0   
5       0.002898      0.000372         0.004375        0.000482          1.0   
6       0.005112      0.002677         0.004496        0.000829          1.5   
7       0.003185      0.000511         0.003893        0.000661          1.5   
8       0.002994      0.000546         0.004188        0.000668          2.0   
9       0.002696      0.000399         0.003616        0.000198          2.0   

   param_norm                         params  split0_test_score  \
0        True   {'alpha': 0.1, 'norm': True}           0.634659   
1       False  {'alpha': 0.1, 'norm': False}           0.599449   
2        True   {'alpha': 0.5, 'norm': True}           0.634659   
3       False  {'alpha': 0.5, 'norm': False}           0.599449   
4        True   {'alpha': 1.0, 'norm': True}           0.634659   
5       False  {'alpha': 1.0, 'norm': False}           0.599449   
6        True   {'alpha': 1.5, 'norm': True}           0.634659   
7       False  {'alpha': 1.5, 'norm': False}           0.599449   
8        True   {'alpha': 2.0, 'norm': True}           0.649225   
9       False  {'alpha': 2.0, 'norm': False}           0.599449   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.650266           0.705612           0.681355           0.699565   
1           0.593122           0.665937           0.795256           0.718256   
2           0.650266           0.705612           0.681355           0.699565   
3           0.593122           0.665937           0.795256           0.718256   
4           0.650266           0.705612           0.650266           0.699565   
5           0.593122           0.665937           0.795256           0.718256   
6           0.650266           0.705612           0.650266           0.699565   
7           0.593122           0.665937           0.795256           0.718256   
8           0.650266           0.705612           0.650266           0.699565   
9           0.593122           0.665937           0.795256           0.718256   

   mean_test_score  std_test_score  rank_test_score  
0         0.674291        0.027632                6  
1         0.674404        0.075927                1  
2         0.674291        0.027632                6  
3         0.674404        0.075927                1  
4         0.668074        0.028815                9  
5         0.674404        0.075927                1  
6         0.668074        0.028815                9  
7         0.674404        0.075927                1  
8         0.670987        0.025876                8  
9         0.674404        0.075927                1