In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('insurance_pre.csv')
df=pd.get_dummies(df,dtype=int,drop_first=True)
df

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
indep=df[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dep=df[['charges']]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep, dep, test_size=1/3, random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [7]:
from sklearn.preprocessing import StandardScaler
scy= StandardScaler()      
y_train=scy.fit_transform(y_train.values.reshape(-1,1))
y_test=scy.transform(y_test.values.reshape(-1,1))

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['friedman_mse','absolute_error','squared_error'],
              'max_features': [None,'sqrt','log2'],
              'n_estimators':[10,100]} 

grid=GridSearchCV(RandomForestRegressor(),param_grid,refit = True, verbose = 3,n_jobs=-1)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits


C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'absolute_error',
                                       'squared_error'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [9]:
from sklearn.metrics import r2_score
y_pred = grid.predict(x_test)
r2_value = r2_score(y_test, y_pred)
print("The R² score value on the test data is: {:.4f}".format(r2_value))

The R² score value on the test data is: 0.8719


In [10]:
re=grid.cv_results_
print("The R² score value for the best parameters {} is: {:.4f}".format(grid.best_params_, grid.best_score_))

table=pd.DataFrame.from_dict(re)
table

The R² score value for the best parameters {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100} is: 0.8027


mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.075485      0.028004         0.006392        0.005514   
1        0.516125      0.077857         0.014359        0.003180   
2        0.041546      0.006920         0.001123        0.001445   
3        0.361981      0.013910         0.015489        0.001387   
4        0.037813      0.006533         0.005757        0.004861   
5        0.353100      0.018870         0.018897        0.004568   
6        0.154671      0.020244         0.003556        0.004609   
7        1.607845      0.156044         0.013252        0.002121   
8        0.102856      0.010902         0.007410        0.008478   
9        0.967213      0.079443         0.012565        0.003472   
10       0.090544      0.006117         0.004919        0.003006   
11       0.905097      0.018096         0.013651        0.003241   
12       0.044137      0.005204         0.004058        0.003430   
13       0.438946      0.012875         0.017521        0.005580   
14       0.036369      0.004875         0.002713        0.003411   
15       0.343409      0.015078         0.015613        0.005909   
16       0.034047      0.005369         0.001603        0.003207   
17       0.296124      0.010902         0.010923        0.002342   

   param_criterion param_max_features  param_n_estimators  \
0     friedman_mse               None                  10   
1     friedman_mse               None                 100   
2     friedman_mse               sqrt                  10   
3     friedman_mse               sqrt                 100   
4     friedman_mse               log2                  10   
5     friedman_mse               log2                 100   
6   absolute_error               None                  10   
7   absolute_error               None                 100   
8   absolute_error               sqrt                  10   
9   absolute_error               sqrt                 100   
10  absolute_error               log2                  10   
11  absolute_error               log2                 100   
12   squared_error               None                  10   
13   squared_error               None                 100   
14   squared_error               sqrt                  10   
15   squared_error               sqrt                 100   
16   squared_error               log2                  10   
17   squared_error               log2                 100   

                                               params  split0_test_score  \
0   {'criterion': 'friedman_mse', 'max_features': ...           0.790270   
1   {'criterion': 'friedman_mse', 'max_features': ...           0.803015   
2   {'criterion': 'friedman_mse', 'max_features': ...           0.797642   
3   {'criterion': 'friedman_mse', 'max_features': ...           0.801450   
4   {'criterion': 'friedman_mse', 'max_features': ...           0.785996   
5   {'criterion': 'friedman_mse', 'max_features': ...           0.800974   
6   {'criterion': 'absolute_error', 'max_features'...           0.770800   
7   {'criterion': 'absolute_error', 'max_features'...           0.791692   
8   {'criterion': 'absolute_error', 'max_features'...           0.818499   
9   {'criterion': 'absolute_error', 'max_features'...           0.802321   
10  {'criterion': 'absolute_error', 'max_features'...           0.787494   
11  {'criterion': 'absolute_error', 'max_features'...           0.803142   
12  {'criterion': 'squared_error', 'max_features':...           0.790544   
13  {'criterion': 'squared_error', 'max_features':...           0.802930   
14  {'criterion': 'squared_error', 'max_features':...           0.790246   
15  {'criterion': 'squared_error', 'max_features':...           0.807736   
16  {'criterion': 'squared_error', 'max_features':...           0.783786   
17  {'criterion': 'squared_error', 'max_features':...           0.807067   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.734891           0.810230   

In [11]:
preinput=sc.transform([[1300,2000,3100,0,1]])
preinput

C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 9.01126003e+01,  3.18738127e+02,  2.57924899e+03,
        -9.88851380e-01,  2.00280702e+00]])

In [12]:
import pickle
filename='final_preprocess_io.sav'

pickle.dump(grid,open(filename,'wb'))


In [13]:
loaded_model=pickle.load(open('final_preprocess_io.sav','rb'))
result=loaded_model.predict(preinput)
result

array([2.67316953])

In [14]:
preoutput=scy.inverse_transform([result])
preoutput


array([[44721.8186328]])