In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('insurance_pre.csv')
df=pd.get_dummies(df,dtype=int,drop_first=True)
df

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
indep=df[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dep=df[['charges']]

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep, dep, test_size=1/3, random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [6]:
from sklearn.preprocessing import StandardScaler
scy= StandardScaler()      
y_train=scy.fit_transform(y_train.values.reshape(-1,1))
y_test=scy.transform(y_test.values.reshape(-1,1))

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['friedman_mse','absolute_error','squared_error'],
              'max_features': [None,'sqrt','log2'],
              'n_estimators':[10,100]} 

grid=GridSearchCV(RandomForestRegressor(),param_grid,refit = True, verbose = 3,n_jobs=-1)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits


C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'absolute_error',
                                       'squared_error'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [8]:
from sklearn.metrics import r2_score
y_pred = grid.predict(x_test)
r2_value = r2_score(y_test, y_pred)
print("The R² score value on the test data is: {:.4f}".format(r2_value))

The R² score value on the test data is: 0.8714


In [9]:
re=grid.cv_results_
print("The R² score value for the best parameters {} is: {:.4f}".format(grid.best_params_, grid.best_score_))

table=pd.DataFrame.from_dict(re)
table

The R² score value for the best parameters {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 100} is: 0.8032


mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.058713      0.009882         0.003812        0.003402   
1        0.479242      0.008129         0.015863        0.003993   
2        0.040005      0.004245         0.004314        0.002680   
3        0.371136      0.017454         0.017459        0.002684   
4        0.041041      0.003091         0.005460        0.003583   
5        0.375887      0.011226         0.016500        0.006766   
6        0.155467      0.004001         0.001711        0.002101   
7        1.478692      0.018865         0.011920        0.003606   
8        0.088259      0.002467         0.002416        0.002959   
9        0.896109      0.032961         0.013498        0.004655   
10       0.085660      0.002543         0.000000        0.000000   
11       0.943386      0.044286         0.014156        0.002994   
12       0.044987      0.004059         0.003199        0.003918   
13       0.431283      0.010392         0.011085        0.002676   
14       0.033018      0.004859         0.001201        0.002402   
15       0.342517      0.009593         0.014891        0.001612   
16       0.031578      0.005374         0.001616        0.003232   
17       0.280679      0.032645         0.009369        0.001062   

   param_criterion param_max_features  param_n_estimators  \
0     friedman_mse               None                  10   
1     friedman_mse               None                 100   
2     friedman_mse               sqrt                  10   
3     friedman_mse               sqrt                 100   
4     friedman_mse               log2                  10   
5     friedman_mse               log2                 100   
6   absolute_error               None                  10   
7   absolute_error               None                 100   
8   absolute_error               sqrt                  10   
9   absolute_error               sqrt                 100   
10  absolute_error               log2                  10   
11  absolute_error               log2                 100   
12   squared_error               None                  10   
13   squared_error               None                 100   
14   squared_error               sqrt                  10   
15   squared_error               sqrt                 100   
16   squared_error               log2                  10   
17   squared_error               log2                 100   

                                               params  split0_test_score  \
0   {'criterion': 'friedman_mse', 'max_features': ...           0.807544   
1   {'criterion': 'friedman_mse', 'max_features': ...           0.802915   
2   {'criterion': 'friedman_mse', 'max_features': ...           0.762007   
3   {'criterion': 'friedman_mse', 'max_features': ...           0.809480   
4   {'criterion': 'friedman_mse', 'max_features': ...           0.791133   
5   {'criterion': 'friedman_mse', 'max_features': ...           0.810346   
6   {'criterion': 'absolute_error', 'max_features'...           0.759105   
7   {'criterion': 'absolute_error', 'max_features'...           0.783599   
8   {'criterion': 'absolute_error', 'max_features'...           0.806748   
9   {'criterion': 'absolute_error', 'max_features'...           0.799293   
10  {'criterion': 'absolute_error', 'max_features'...           0.775103   
11  {'criterion': 'absolute_error', 'max_features'...           0.799477   
12  {'criterion': 'squared_error', 'max_features':...           0.772380   
13  {'criterion': 'squared_error', 'max_features':...           0.806490   
14  {'criterion': 'squared_error', 'max_features':...           0.763421   
15  {'criterion': 'squared_error', 'max_features':...           0.804408   
16  {'criterion': 'squared_error', 'max_features':...           0.779441   
17  {'criterion': 'squared_error', 'max_features':...           0.806052   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.745506           0.828775   

In [10]:
preinput=sc.transform([[1300,2000,3100,0,1]])
preinput

C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 9.01126003e+01,  3.18738127e+02,  2.57924899e+03,
        -9.88851380e-01,  2.00280702e+00]])

In [11]:
import pickle
filename='final_preprocess_io.sav'

pickle.dump(grid,open(filename,'wb'))


In [12]:
loaded_model=pickle.load(open('final_preprocess_io.sav','rb'))
result=loaded_model.predict(preinput)
result

array([2.43474411])

In [13]:
preoutput=scy.inverse_transform([result])
preoutput


array([[41904.822531]])

In [14]:
import pickle
f1='std_scaler_model.pkl'
pickle.dump(sc,open(f1,'wb'))

f2='std_scaler_y_model.pkl'
pickle.dump(scy,open(f2,'wb'))



In [15]:
loaded_model=pickle.load(open('std_scaler_model.pkl','rb'))
loaded_model=pickle.load(open('std_scaler_y_model.pkl','rb'))