In [1]:
import pandas as pd
import numpy as py
import pickle

In [2]:
df=pd.read_csv('insurance_pre.csv')
df=pd.get_dummies(df,dtype=int,drop_first=True)
indep=df[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=df['charges']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep, dep, test_size=1/3, random_state=0)

In [3]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)


In [4]:
scy= StandardScaler()      
y_train=scy.fit_transform(y_train.values.reshape(-1,1))
y_test=scy.transform(y_test.values.reshape(-1,1))

In [5]:
preinput=sc.transform([[1300,2000,3100,0,1]])
preinput

C:\Users\Hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 9.01126003e+01,  3.18738127e+02,  2.57924899e+03,
        -9.88851380e-01,  2.00280702e+00]])

In [6]:
loaded_model=pickle.load(open('final_preprocess_io.sav','rb'))
result=loaded_model.predict(preinput)
result

array([2.67316953])

In [8]:
preoutput=scy.inverse_transform(result.reshape(-1, 1))
preoutput

array([[44721.8186328]])